-- 코드를 입력하세요
SELECT B.AUTHOR_ID , A.AUTHOR_NAME , B.CATEGORY , SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE,"%Y-%m")='2022-01'
GROUP BY CATEGORY , AUTHOR_ID
ORDER BY AUTHOR_ID , CATEGORY DESC