-- 렌트 불가능한 CAR_ID

-- SELECT *
--   FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
--  WHERE C.CAR_ID NOT IN (SELECT DISTINCT CAR_ID 
--                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--                          WHERE (TO_DATE('20221101','YYYYMMDD') >= START_DATE AND TO_DATE('20221130','YYYYMMDD') >= END_DATE)
--                             OR (TO_DATE('20221101','YYYYMMDD') >= END_DATE AND TO_DATE('20221130','YYYYMMDD') <= END_DATE)
--                             OR (TO_DATE('20221101','YYYYMMDD') >= START_DATE AND TO_DATE('20221130','YYYYMMDD') <= END_DATE)
--                             OR (TO_DATE('20221101','YYYYMMDD') >=  START_DATE AND TO_DATE('20221130','YYYYMMDD') <= START_DATE))
--     AND  C.CAR_TYPE = P.CAR_TYPE 
--     AND C.DAILY_FEE * 31 * (100-TO_NUMBER(REPLACE(P.DISCOUNT_RATE,'%',''))/100) >= 500000
--     AND C.DAILY_FEE * 31 * (100- TO_NUMBER(REPLACE(P.DISCOUNT_RATE,'%','')/100) <= 2000000


-- SELECT DISTINCT CAR_ID 
--   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--  WHERE (TO_DATE('20221101','YYYYMMDD') >= START_DATE AND TO_DATE('20221130','YYYYMMDD') >= END_DATE)
--     OR (TO_DATE('20221101','YYYYMMDD') >= END_DATE AND TO_DATE('20221130','YYYYMMDD') <= END_DATE)
--     OR (TO_DATE('20221101','YYYYMMDD') >= START_DATE AND TO_DATE('20221130','YYYYMMDD') <= END_DATE)
--     OR (TO_DATE('20221101','YYYYMMDD') >=  START_DATE AND TO_DATE('20221130','YYYYMMDD') <= START_DATE)
    
    
    SELECT C.CAR_ID, C.CAR_TYPE,
       ROUND(C.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE,'%',''))) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE '2022-11-30'
      AND END_DATE   >= DATE '2022-11-01'
)
AND C.CAR_TYPE IN ('SUV', '세단')
AND P.DURATION_TYPE = '30일 이상'
AND ROUND(C.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE,'%',''))) / 100)
    BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
