-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR , MONTH(SALES_DATE) AS MONTH ,
        U.GENDER,COUNT( DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE S
INNER JOIN USER_INFO U ON U.USER_ID = S.USER_ID
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER