-- 코드를 입력하세요
SELECT 
YEAR(S.SALES_DATE) AS YEAR ,
MONTH(S.SALES_DATE) AS MONTH,
COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED)='2021'),1)
AS PUCHASED_RATIO

FROM ONLINE_SALE S
INNER JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED)='2021'
GROUP BY YEAR(SALES_DATE) , MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE) , MONTH(SALES_DATE)
