-- 코드를 입력하세요
SELECT APNT_NO , PT_NAME , A.PT_NO , A.MCDP_CD, D.DR_NAME , APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD='CS' AND DATE_FORMAT(APNT_YMD,"%m-%d")='04-13' AND APNT_CNCL_YN='N'
ORDER BY APNT_YMD
