# 아이템의 희귀도가 RARE인 아이템들의 모든 다음 업그레이드 아이템의 아이템 필드를 출력
SELECT I.ITEM_ID , I.ITEM_NAME , I.RARITY
FROM ITEM_INFO I
INNER JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID
              FROM ITEM_INFO 
              WHERE RARITY="RARE")
ORDER BY I.ITEM_ID DESC